FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "KrediHesaplama.Api.csproj"
RUN dotnet publish "KrediHesaplama.Api.csproj" -c Release -o /app

FROM mcr.microsoft.com AS final
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "KrediHesaplama.Api.dll"]
