FROM ://microsoft.com AS build
WORKDIR /src

# Klasördeki her şeyi kopyala
COPY . . 

RUN dotnet restore
RUN dotnet publish -c Release -o /app

FROM ://microsoft.com AS final
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "KrediHesaplama.Api.dll"]
